"""Add end_time to Show and create ArtistAvailability models

Revision ID: 09a743206f49
Revises: 957a1d37b74c
Create Date: 2026-08-29 00:05:29.295030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a743206f49'
down_revision = '957a1d37b74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'day_of_week', 'start_time', 'end_time', name='uq_artist_availability_slot')
    )
    op.create_table('artist_availability_exception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'exception_date', name='uq_artist_availability_exception')
    )
    with op.batch_alter_table('show', schema=None) as batch_op:
        # Add end_time as nullable first
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
    
    # Update existing shows: set end_time = start_time + 1 hour
    op.execute("""
        UPDATE "show" 
        SET end_time = start_time + INTERVAL '1 hour'
        WHERE end_time IS NULL
    """)
    
    # Now alter column to NOT NULL
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('end_time', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    op.drop_table('artist_availability_exception')
    op.drop_table('artist_availability')
    # ### end Alembic commands ###
