"""Add created_at timestamp to Artist and Venue models

Revision ID: 8389b11d0662
Revises: 4663fa2fd612
Create Date: 2026-08-28 23:21:53.645382

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '8389b11d0662'
down_revision = '4663fa2fd612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
    
    # Update existing rows with current timestamp
    op.execute("UPDATE artist SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE venue SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    
    # Now make the columns NOT NULL
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)

    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
