"""Add created_at timestamp to Show and Genre models

Revision ID: 957a1d37b74c
Revises: 8389b11d0662
Create Date: 2026-08-28 23:24:32.242053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957a1d37b74c'
down_revision = '8389b11d0662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # Update existing rows with current timestamp
    op.execute("UPDATE genre SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    op.execute("UPDATE show SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")

    # Now make the columns NOT NULL
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)

    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('show', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
